
log4j.rootLogger=info, stdout, file

log4j.category.com.jolbox=debug, stdout
log4j.logger.com.mchange=warn, file

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{MM-dd@HH:mm:ss} %-5p (%13c) - %m%n

log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=log/openadr3-client.log
log4j.appender.file.MaxFileSize=1000KB
log4j.appender.file.MaxBackupIndex=1
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{MM-dd@HH:mm:ss} %-5p (%13c) - %m%n

log4j.logger.javax.jmdns.impl=debug, mdnsappender
log4j.additivity.javax.jmdns.impl=false

log4j.appender.mdnsappender=org.apache.log4j.DailyRollingFileAppender
log4j.appender.mdnsappender.File=log/mDNS.log
log4j.appender.mdnsappender.layout=org.apache.log4j.PatternLayout
log4j.appender.mdnsappender.layout.ConversionPattern=%d{MM-dd@HH:mm:ss} %-5p (%13c) - %m%n
